# -*- coding: utf-8 -*
import os

curPath = os.path.abspath(os.path.dirname(__file__))
root_path = os.path.split(curPath)[0]
from utils import utils

users_path = os.path.join(root_path, "config/users.json")
error_sign_path = os.path.join(root_path, "config/error_sign.json")
error_form_path = os.path.join(root_path, "config/error_form.json")
error_pwd_path = os.path.join(root_path, "config/error_pwd.json")

loger = utils.get_log()

form = [{'compt': 'captiontext',
         'id': 2,
         'fields': [{'tip': {'imgs': [], 'text': '研究生新型冠状肺炎信息调查项目'},
                     'label': '说明文字',
                     'fieldType': {'type': 'string'}}],
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'captiontext',
         'id': 3,
         'fields': [{'tip': {'imgs': [],
                             'text': '全体研究生：为了准确了解和把握广大同学的现实状态，积极开展新型冠状肺炎的防控工作，学校专门设计了新型冠状肺炎信息调查，请同学们本着认真负责的态度如实填写，感谢配合，谢谢！'},
                     'label': '说明文字',
                     'fieldType': {'type': 'string'}}],
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 25,
         'fields': [{'values': [{'val': 'A:无变化（选择此项后，可直接点击提交）'}],
                     'options': [{'idArr': [],
                                  'checked': True,
                                  'title': 'A:无变化（选择此项后，可直接点击提交）'},
                                 {'idArr': [],
                                  'checked': False,
                                  'title': 'B:有变化（选择此项后，请在以下有变化题目填写，其他未填写题目系统默认为无变化）'}],
                     'verify': {'required': {}},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '1.与上次填报信息相比，有无变化？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'linkInfo': {'linkFormCondFieldId': 0,
                      'linkFormType': '',
                      'linkFormId': 0,
                      'linkFormIdEnc': '',
                      'linkFormValueFieldId': 0,
                      'linked': False,
                      'currFormCondFieldId': 0},
         'compt': 'editinput',
         'latestValShow': False,
         'id': 28,
         'fields': [{'values': [{'val': '陕西省西安市长安区郭杜街道陕西师范大学长安校区'}],
                     'verify': {'format': {'type': ''}, 'required': {}},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '2.你目前所在地？（精确到区县，例：xx省xx市xx区/xx县）',
                     'fieldType': {'type': 'string'}}],
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'checklist',
         'comptCombined': True,
         'latestValShow': False,
         'id': 15,
         'fields': [{'values': [{'val': 'F:无症状'}],
                     'options': [{'checked': False, 'title': 'A:发热（37.3度以上）'},
                                 {'checked': False, 'title': 'B:咳嗽，呼吸困难'},
                                 {'checked': False, 'title': 'C:咽喉疼痛'},
                                 {'checked': False, 'title': 'D:头疼'},
                                 {'checked': False, 'title': 'E:流鼻涕'},
                                 {'checked': True, 'title': 'F:无症状'}],
                     'verify': {'minValue': {'errMsg': '输入的值不能小于', 'range': 0},
                                'maxValue': {'errMsg': '输入的值不能大于', 'range': 0},
                                'required': {}},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '3.你最近身体的不适症状？',
                     'fieldType': {'type': 'string'}}],
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 29,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A.是'},
                                 {'idArr': [], 'checked': False, 'title': 'B.否'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '4.你是否在陕西？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 5,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:在陕西学生请选此选项'},
                                 {'idArr': [], 'checked': False, 'title': 'B:高风险等级区域（非在陕学生）'},
                                 {'idArr': [], 'checked': False, 'title': 'C.中风险等级区域（非在陕学生）'},
                                 {'idArr': [], 'checked': False, 'title': 'D.低风险等级区域（非在陕学生）'}],
                     'verify': {},
                     'tip': {'imgs': [],
                             'text': '请使用国务院开发的微信小程序“疫情风险等级查询”填写此题目，在陕学生无需查询，勾选A选项即可。'},
                     'label': '5.你目前所在地属于哪类风险等级区域？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 27,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A.飞机'},
                                 {'idArr': [], 'checked': False, 'title': 'B.火车'},
                                 {'idArr': [], 'checked': False, 'title': 'C.其他'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '6.你计划从目前所在地返校主要乘坐何种交通工具？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 4,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:中国内陆地区'},
                                 {'idArr': [], 'checked': False, 'title': 'B:港澳台地区'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '7.你的籍贯所在区域？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 6,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:是，在学生宿舍居住'},
                                 {'idArr': [], 'checked': False, 'title': 'B:是，在学校家属区居住'},
                                 {'idArr': [], 'checked': False, 'title': 'C:是，在校内其他地点居住'},
                                 {'idArr': [], 'checked': False, 'title': 'D:否，不在校居住'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '8.目前是否在校居住？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'linkInfo': {'linkFormCondFieldId': 0,
                      'linkFormType': '',
                      'linkFormId': 0,
                      'linkFormIdEnc': '',
                      'linkFormValueFieldId': 0,
                      'linked': False,
                      'currFormCondFieldId': 0},
         'compt': 'editinput',
         'latestValShow': False,
         'id': 7,
         'fields': [{'values': [{'val': ''}],
                     'verify': {'format': {'type': ''}},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '9.目前在校居住地址（具体到房号）？',
                     'fieldType': {'type': 'string'}}],
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 8,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:是'},
                                 {'idArr': [], 'checked': False, 'title': 'B:否'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '10.你是否被医院确诊为新型肺炎病例？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 9,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:是'},
                                 {'idArr': [], 'checked': False, 'title': 'B:否'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '11.你是否被医院确诊为新型肺炎疑似病例？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 10,
         'fields': [{'values': [],
                     'options': [{'idArr': [],
                                  'checked': False,
                                  'title': 'A:是，医学观察隔离（在医院或者个人单独居住由医护人员跟进隔离）'},
                                 {'idArr': [], 'checked': False, 'title': 'B:是，居家隔离'},
                                 {'idArr': [], 'checked': False, 'title': 'C:否，无措施'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '12.你是否进行隔离防护？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 24,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:1人'},
                                 {'idArr': [], 'checked': False, 'title': 'B:2人'},
                                 {'idArr': [], 'checked': False, 'title': 'C:3人'},
                                 {'idArr': [], 'checked': False, 'title': 'D:4人'},
                                 {'idArr': [], 'checked': False, 'title': 'E:5人'},
                                 {'idArr': [], 'checked': False, 'title': 'F:5人以上'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '13.如果你正在居家隔离，家庭隔离人数为多少？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 11,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:是'},
                                 {'idArr': [], 'checked': False, 'title': 'B:否'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '14.你是否出现有发烧、咳嗽、呼吸管困难等疑似症状？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 12,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:是'},
                                 {'idArr': [], 'checked': False, 'title': 'B:否'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '15.如被确诊为新型肺炎，是否已治愈出院？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 13,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:是，确诊病例'},
                                 {'idArr': [], 'checked': False, 'title': 'B:是，疑似病例'},
                                 {'idArr': [], 'checked': False, 'title': 'C:否'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '16.你的家人是否被医院确诊为新型肺炎病例或含疑似病例？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 14,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:是，接触过确诊病例'},
                                 {'idArr': [], 'checked': False, 'title': 'B:是，接触过疑似病例'},
                                 {'idArr': [], 'checked': False, 'title': 'C:否'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '17.你是否接触过被医院确诊为新型肺炎病例或疑似病例的人员？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 16,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A：是'},
                                 {'idArr': [], 'checked': False, 'title': 'B：否'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '18.近15日内是否有与湖北人员接触？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 17,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A：是'},
                                 {'idArr': [], 'checked': False, 'title': 'B：否'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '19.近15日内是否有与武汉人员有过接触？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 19,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:不曾去过湖北'},
                                 {'idArr': [], 'checked': False, 'title': 'B:返家或旅行途中在湖北中转'},
                                 {'idArr': [], 'checked': False, 'title': 'C:有去湖北所属省市旅游或者探亲'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '20.近15日内是否去过或者途径湖北中转？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 20,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:我已知晓，并严格遵守规定'},
                                 {'idArr': [], 'checked': False, 'title': 'B:我不知晓，未接到相关通知'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '21.学校延迟开学的通知和2月14日之前不能返校的要求，你是否知晓并严格遵守规定？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'linkInfo': {'linkFormCondFieldId': 0,
                      'linkFormType': '',
                      'linkFormId': 0,
                      'linkFormIdEnc': '',
                      'linkFormValueFieldId': 0,
                      'linked': False,
                      'currFormCondFieldId': 0},
         'compt': 'editinput',
         'latestValShow': True,
         'id': 21,
         'fields': [{'values': [{'val': ''}],
                     'verify': {'format': {'type': ''}},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '22.你的导师姓名？',
                     'fieldType': {'type': 'string'}}],
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'compt': 'radiobutton',
         'comptCombined': True,
         'latestValShow': False,
         'id': 22,
         'fields': [{'values': [],
                     'options': [{'idArr': [], 'checked': False, 'title': 'A:我已联系研究生导师'},
                                 {'idArr': [], 'checked': False, 'title': 'B:我已联系研究生辅导员'},
                                 {'idArr': [], 'checked': False, 'title': 'C:我已联系研究生辅导员及导师'},
                                 {'idArr': [], 'checked': False, 'title': 'D:均未取得联系'}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '23.你是否已与研究生导师及辅导员取得联系，并随时汇报情况？',
                     'fieldType': {'type': 'string'}}],
         'optionScoreShow': False,
         'optionScoreUsed': False,
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True},
        {'linkInfo': {'linkFormCondFieldId': 0,
                      'linkFormType': '',
                      'linkFormId': 0,
                      'linkFormIdEnc': '',
                      'linkFormValueFieldId': 0,
                      'linked': False,
                      'currFormCondFieldId': 0},
         'compt': 'edittextarea',
         'latestValShow': True,
         'id': 23,
         'fields': [{'values': [{'val': ''}],
                     'verify': {},
                     'tip': {'imgs': [], 'text': ''},
                     'label': '24.你对学校当前关于新型冠状肺炎防控工作有何意见和建议：',
                     'fieldType': {'type': 'string'}}],
         'inDetailGroupIndex': -1,
         'fromDetail': False,
         'isShow': True}]
form_c = [{'compt': 'captiontext',
           'id': 1,
           'fields': [{'tip': {'imgs': [],
                               'text': '全体研究生：&nbsp; 结合当前疫情防控常态化形势，研究生开学返校后校园实行封闭式管理，执行一日一检一报制度，即体温晨检晨报。请大家本着认真负责的态度做好体温监测。'},
                       'label': '说明文字',
                       'fieldType': {'type': 'string'}}],
           'inDetailGroupIndex': -1,
           'fromDetail': False,
           'isShow': True},
          {'linkInfo': {'linkFormCondFieldId': 0,
                        'linkFormType': '',
                        'linkFormId': 0,
                        'linkFormIdEnc': '',
                        'linkFormValueFieldId': 0,
                        'linked': False,
                        'currFormCondFieldId': 0},
           'compt': 'editinput',
           'latestValShow': False,
           'id': 3,
           'fields': [{'values': [{'val': '36.2'}],
                       'verify': {'format': {'type': ''}, 'required': {}},
                       'tip': {'imgs': [], 'text': '（精确到小数点1位，填写示例：36.3℃）'},
                       'label': '1.早上体温测量为多少度？',
                       'sweepCode': False,
                       'fieldType': {'type': 'string'},
                       'codeChangeable': False}],
           'inDetailGroupIndex': -1,
           'fromDetail': False,
           'isShow': True},
          {'compt': 'radiobutton',
           'comptCombined': True,
           'latestValShow': False,
           'id': 5,
           'fields': [{'values': [{'val': '是'}],
                       'options': [{'idArr': [], 'score': 0, 'checked': True, 'title': '是'},
                                   {'idArr': [], 'score': 0, 'checked': False, 'title': '否'}],
                       'verify': {'required': {}},
                       'tip': {'imgs': [], 'text': ''},
                       'label': '2.我保证以上所填信息真实，无隐瞒，将严格遵守学校管理制度！',
                       'fieldType': {'type': 'string'}}],
           'optionScoreShow': False,
           'optionScoreUsed': False,
           'inDetailGroupIndex': -1,
           'fromDetail': False,
           'isShow': True}]
